[package]
name = "decompress_regex"
version = "0.1.0"
authors = ["toku-sa-n <42336339+toku-sa-n@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
